name: sidbi_app
description: "Web Application/Mobile app will be used by retirees to download pension slip/estimates and can apply for reimbursement of OPD/CHC. They can apply for book VOF/Holiday Home and same will be forwarded to desk for approval. They can declare tax savings and upload Life certificate and same will be intimated / forwarded to eefc /pension cell for further processing."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+11

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts:
  http:
  pinput: ^5.0.0
  shared_preferences:
  syncfusion_flutter_datepicker: ^26.1.41
  file_picker: 8.1.4
  timeline_tile: ^2.0.0
  crypto: ^3.0.3
  intl: ^0.19.0
  path_provider: ^2.1.3
  flutter_pdfview: ^1.3.2
  webview_flutter: ^4.8.0
  permission_handler: ^11.3.1
  upgrader:
  hive:
  build_runner:
  hive_flutter:
  dotted_border: ^2.1.0
  flutter_launcher_icons: ^0.14.1
  sizer: ^3.0.4
  change_app_package_name: ^1.4.0
#  firebase_messaging: ^15.1.6
  in_app_update: ^4.2.3
  crypto_dart: ^1.0.3+2
  encrypt: ^5.0.3
  syncfusion_flutter_pdf: ^26.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lc_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

